### ISSUE TITLE
An error occurred when blasting the flag length

### ISSUE THREAD

**Issue by D1ag0n-Young** [ChrisTheCoolHut/PinCTF#18]
An error occurred when blasting the flag length, and a lot of pin_AA folders were generated, prompting that the inscount.out file could not be found. After reading the python source code, I found that the pin output result was not output to the pin_AA/inscount.out file.

as follows：
```bash
➜  PinCTF git:(master) ✗ python3 pinCTF.py -f examples/test -il -l ./obj-intel64 -c 10

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "pinCTF.py", line 450, in runThreadedCommandWrapper
    return runThreadedCommand(mapped_data[0], mapped_data[1], mapped_data[2], mapped_data[3], mapped_data[4], mapped_data[5], mapped_data[6])
  File "pinCTF.py", line 466, in runThreadedCommand
    count = sendPinInputCommandThread(pin,library,binary,path,item)
  File "pinCTF.py", line 204, in sendPinInputCommandThread
    count = readCount("pin_{}/inscount.out".format(ident))
  File "pinCTF.py", line 144, in readCount
    inscountFile = open(inscountFileName)
FileNotFoundError: [Errno 2] No such file or directory: 'pin_A/inscount.out'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pinCTF.py", line 469, in <module>
    main()
  File "pinCTF.py", line 96, in main
    inputLengthTuple = pinLength(pinLocation,libraryLocation,args.file,count,arg=False, multi_core=int(args.threadCount))
  File "pinCTF.py", line 221, in pinLength
    for i in m_pool.imap_unordered(runThreadedCommandWrapper, arg_list):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'pin_A/inscount.out'
```
The pin.log below pin_A is displayed as follows:
```bash
Pin: pin-3.11-97998-7ecce2dac
Copyright 2002-2019 Intel Corporation.
E:  Unable to load ./obj-intel64/inscount0.so
```
But this file exists

**Comment by ChrisTheCoolHut** [comment]
I wrote this tool a while ago and didn't convert it's arguments to absolute paths, so hopefully the fix is just adding the full path to the -l flag:
```
python3 pinCTF.py -f examples/test -il -l $(pwd)/obj-intel64 -c 10
```

**Comment by D1ag0n-Young** [comment]
Thank you very much, the problem is solved
