### ISSUE TITLE
some wrong on install

### ISSUE THREAD

**Issue by MuRKuo** [ChrisTheCoolHut/PinCTF#19]
I use the `installPin.sh` to install Pin ,but whern i run the `python3 pinCTF.py -f examples/wyvern_c85f1be480808a9da350faaa6104a19b -il -l obj-intel64/ -c 30`
something is error ,i install the package for need at first ,but it still occur
```
┌─(/home/mosen/Desktop/PinCTF)────────────────────────────(ROOT@ubuntu:pts/0)─┐
└─(06:09:36 on master ✭)──> python3 pinCTF.py -f examples/wyvern_c85f1be480808a9da350faaa6104a19b -il -l obj-intel64/ -c 30
sh: 1: sh: 1: /pin: not found
/pin: not found
sh: 1: /pin: not found
sh: 1: /pin: not found
sh: echo: I/O error
sh: 1: /pin: not found
sh: echo: I/O error
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "pinCTF.py", line 450, in runThreadedCommandWrapper
    return runThreadedCommand(mapped_data[0], mapped_data[1], mapped_data[2], mapped_data[3], mapped_data[4], mapped_data[5], mapped_data[6])
  File "pinCTF.py", line 466, in runThreadedCommand
    count = sendPinInputCommandThread(pin,library,binary,path,item)
  File "pinCTF.py", line 204, in sendPinInputCommandThread
    count = readCount("pin_{}/inscount.out".format(ident))
  File "pinCTF.py", line 144, in readCount
    inscountFile = open(inscountFileName)
FileNotFoundError: [Errno 2] No such file or directory: 'pin_A/inscount.out'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pinCTF.py", line 469, in <module>
    main()
  File "pinCTF.py", line 96, in main
    inputLengthTuple = pinLength(pinLocation,libraryLocation,args.file,count,arg=False, multi_core=int(args.threadCount))
  File "pinCTF.py", line 221, in pinLength
    for i in m_pool.imap_unordered(runThreadedCommandWrapper, arg_list):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'pin_A/inscount.out'
sh: 1: /pin: not found
sh: echo: I/O error
sh: 1: /pin: not found
```

**Comment by MuRKuo** [comment]
```
└─(06:13:49 on master ✭)──> python3 --version                                                                                                                              ──(Sat,Oct23)─┘
Python 3.6.9
┌─(/home/mosen/Desktop/PinCTF)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@ubuntu:pts/0)─┐
└─(06:16:15 on master ✭)──> pip3 --version                                                                                                                                 ──(Sat,Oct23)─┘
pip 21.2.4 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```
this is my pip and python version
